### ISSUE TITLE
"Custom CSS class:" option doesn't work

### ISSUE THREAD

**Issue by piotrkunicki** [GavickPro/GK-Widget-Rules#6]
When I add i.e. these classess: class1 class2 class3 and save widget this filed looks like:
class1class2class3 and classess are not visible in the widget's code.

**Comment by dziudek** [comment]
In which theme did you made the tests? On 2014 the classes appears for me on the content sidebar widget area.

The problem with spaces has been fixed: https://github.com/GavickPro/GK-Widget-Rules/commit/b26457cb54394f7a1ab807baed6fb93cb418e061

**Comment by piotrkunicki** [comment]
It's weird, I've checked on the Event theme previously, now on the 2014 - the same sidebar widget area and still can't see css class:
![sponsors___events](https://cloud.githubusercontent.com/assets/2950258/3992987/89bef71a-2905-11e4-8833-41b88c486b17.jpg)

**Comment by dziudek** [comment]
Problem should be fixed now: https://github.com/GavickPro/GK-Widget-Rules/commit/5e9e98d5757e8b7224399b3b60fa5931691f1b42

**Comment by piotrkunicki** [comment]
yes, it works now.
